package com.shawn.finance.assetmanagement.model;

import java.util.Date;

public class AssetPlan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_plan.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_plan.am_id
     *
     * @mbggenerated
     */
    private Long amId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_plan.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_plan.contract
     *
     * @mbggenerated
     */
    private String contract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_plan.protocol
     *
     * @mbggenerated
     */
    private String protocol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_plan.transfer_time
     *
     * @mbggenerated
     */
    private Date transferTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_plan.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_plan.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_plan.id
     *
     * @return the value of tbl_asset_plan.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_plan.id
     *
     * @param id the value for tbl_asset_plan.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_plan.am_id
     *
     * @return the value of tbl_asset_plan.am_id
     *
     * @mbggenerated
     */
    public Long getAmId() {
        return amId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_plan.am_id
     *
     * @param amId the value for tbl_asset_plan.am_id
     *
     * @mbggenerated
     */
    public void setAmId(Long amId) {
        this.amId = amId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_plan.name
     *
     * @return the value of tbl_asset_plan.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_plan.name
     *
     * @param name the value for tbl_asset_plan.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_plan.contract
     *
     * @return the value of tbl_asset_plan.contract
     *
     * @mbggenerated
     */
    public String getContract() {
        return contract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_plan.contract
     *
     * @param contract the value for tbl_asset_plan.contract
     *
     * @mbggenerated
     */
    public void setContract(String contract) {
        this.contract = contract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_plan.protocol
     *
     * @return the value of tbl_asset_plan.protocol
     *
     * @mbggenerated
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_plan.protocol
     *
     * @param protocol the value for tbl_asset_plan.protocol
     *
     * @mbggenerated
     */
    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_plan.transfer_time
     *
     * @return the value of tbl_asset_plan.transfer_time
     *
     * @mbggenerated
     */
    public Date getTransferTime() {
        return transferTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_plan.transfer_time
     *
     * @param transferTime the value for tbl_asset_plan.transfer_time
     *
     * @mbggenerated
     */
    public void setTransferTime(Date transferTime) {
        this.transferTime = transferTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_plan.create_time
     *
     * @return the value of tbl_asset_plan.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_plan.create_time
     *
     * @param createTime the value for tbl_asset_plan.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_plan.update_time
     *
     * @return the value of tbl_asset_plan.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_plan.update_time
     *
     * @param updateTime the value for tbl_asset_plan.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}