package com.shawn.finance.assetmanagement.model;

import java.util.Date;

public class AssetCustomer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_customer.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_customer.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_customer.gender
     *
     * @mbggenerated
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_customer.age
     *
     * @mbggenerated
     */
    private Byte age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_customer.degree
     *
     * @mbggenerated
     */
    private Byte degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_customer.profession
     *
     * @mbggenerated
     */
    private String profession;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_customer.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_customer.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_customer.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_customer.id
     *
     * @return the value of tbl_asset_customer.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_customer.id
     *
     * @param id the value for tbl_asset_customer.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_customer.name
     *
     * @return the value of tbl_asset_customer.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_customer.name
     *
     * @param name the value for tbl_asset_customer.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_customer.gender
     *
     * @return the value of tbl_asset_customer.gender
     *
     * @mbggenerated
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_customer.gender
     *
     * @param gender the value for tbl_asset_customer.gender
     *
     * @mbggenerated
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_customer.age
     *
     * @return the value of tbl_asset_customer.age
     *
     * @mbggenerated
     */
    public Byte getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_customer.age
     *
     * @param age the value for tbl_asset_customer.age
     *
     * @mbggenerated
     */
    public void setAge(Byte age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_customer.degree
     *
     * @return the value of tbl_asset_customer.degree
     *
     * @mbggenerated
     */
    public Byte getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_customer.degree
     *
     * @param degree the value for tbl_asset_customer.degree
     *
     * @mbggenerated
     */
    public void setDegree(Byte degree) {
        this.degree = degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_customer.profession
     *
     * @return the value of tbl_asset_customer.profession
     *
     * @mbggenerated
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_customer.profession
     *
     * @param profession the value for tbl_asset_customer.profession
     *
     * @mbggenerated
     */
    public void setProfession(String profession) {
        this.profession = profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_customer.create_time
     *
     * @return the value of tbl_asset_customer.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_customer.create_time
     *
     * @param createTime the value for tbl_asset_customer.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_customer.update_time
     *
     * @return the value of tbl_asset_customer.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_customer.update_time
     *
     * @param updateTime the value for tbl_asset_customer.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_customer.status
     *
     * @return the value of tbl_asset_customer.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_customer.status
     *
     * @param status the value for tbl_asset_customer.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}