package com.shawn.finance.assetmanagement.model;

import java.util.Date;

public class AssetManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_manager.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_manager.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_manager.bank_name
     *
     * @mbggenerated
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_manager.branch_bank_name
     *
     * @mbggenerated
     */
    private String branchBankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_manager.bank_card
     *
     * @mbggenerated
     */
    private String bankCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_manager.bank_card_type
     *
     * @mbggenerated
     */
    private Integer bankCardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_manager.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_manager.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_manager.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_manager.id
     *
     * @return the value of tbl_asset_manager.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_manager.id
     *
     * @param id the value for tbl_asset_manager.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_manager.name
     *
     * @return the value of tbl_asset_manager.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_manager.name
     *
     * @param name the value for tbl_asset_manager.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_manager.bank_name
     *
     * @return the value of tbl_asset_manager.bank_name
     *
     * @mbggenerated
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_manager.bank_name
     *
     * @param bankName the value for tbl_asset_manager.bank_name
     *
     * @mbggenerated
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_manager.branch_bank_name
     *
     * @return the value of tbl_asset_manager.branch_bank_name
     *
     * @mbggenerated
     */
    public String getBranchBankName() {
        return branchBankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_manager.branch_bank_name
     *
     * @param branchBankName the value for tbl_asset_manager.branch_bank_name
     *
     * @mbggenerated
     */
    public void setBranchBankName(String branchBankName) {
        this.branchBankName = branchBankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_manager.bank_card
     *
     * @return the value of tbl_asset_manager.bank_card
     *
     * @mbggenerated
     */
    public String getBankCard() {
        return bankCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_manager.bank_card
     *
     * @param bankCard the value for tbl_asset_manager.bank_card
     *
     * @mbggenerated
     */
    public void setBankCard(String bankCard) {
        this.bankCard = bankCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_manager.bank_card_type
     *
     * @return the value of tbl_asset_manager.bank_card_type
     *
     * @mbggenerated
     */
    public Integer getBankCardType() {
        return bankCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_manager.bank_card_type
     *
     * @param bankCardType the value for tbl_asset_manager.bank_card_type
     *
     * @mbggenerated
     */
    public void setBankCardType(Integer bankCardType) {
        this.bankCardType = bankCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_manager.create_time
     *
     * @return the value of tbl_asset_manager.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_manager.create_time
     *
     * @param createTime the value for tbl_asset_manager.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_manager.update_time
     *
     * @return the value of tbl_asset_manager.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_manager.update_time
     *
     * @param updateTime the value for tbl_asset_manager.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_manager.status
     *
     * @return the value of tbl_asset_manager.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_manager.status
     *
     * @param status the value for tbl_asset_manager.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}