package com.shawn.finance.assetmanagement.model;

import java.util.Date;

public class AssetMerchant {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_merchant.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_merchant.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_merchant.branch_name
     *
     * @mbggenerated
     */
    private String branchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_merchant.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_merchant.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_asset_merchant.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_merchant.id
     *
     * @return the value of tbl_asset_merchant.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_merchant.id
     *
     * @param id the value for tbl_asset_merchant.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_merchant.name
     *
     * @return the value of tbl_asset_merchant.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_merchant.name
     *
     * @param name the value for tbl_asset_merchant.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_merchant.branch_name
     *
     * @return the value of tbl_asset_merchant.branch_name
     *
     * @mbggenerated
     */
    public String getBranchName() {
        return branchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_merchant.branch_name
     *
     * @param branchName the value for tbl_asset_merchant.branch_name
     *
     * @mbggenerated
     */
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_merchant.create_time
     *
     * @return the value of tbl_asset_merchant.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_merchant.create_time
     *
     * @param createTime the value for tbl_asset_merchant.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_merchant.update_time
     *
     * @return the value of tbl_asset_merchant.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_merchant.update_time
     *
     * @param updateTime the value for tbl_asset_merchant.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_asset_merchant.status
     *
     * @return the value of tbl_asset_merchant.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_asset_merchant.status
     *
     * @param status the value for tbl_asset_merchant.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}